--- 
script: make release-all
before_script: 
  - pushd /home/travis/.gvm/gos/go1.1.1/src
  - ./make.bash
  - popd
go: 
  - 1.1
after_success: NGROK=bin/$GOOS_$GOARCH/ngrok NGROKD=bin/$GOOS_$GOARCH/ngrokd $UPLOAD
env: 
  matrix: 
    - GOOS=linux GOARCH=arm
    - GOOS=linux GOARCH=386
    - GOOS=windows GOARCH=386
  global: 
    secure: V/hOxdpBks7y1RKcXzEWnnXss5VLDhNe0a6tdiBT9V+WUH8wd3dXKpDQeKGBESUiypnq3zTz1sq8sFPxgJYaYGyto+naWL5Hz3ZFNvgnIVKBlmdwoyxL2kIBHIAeqdTiOfjPEiNPC0a0URyuyXX3T/sGrRrIkthyca9jR3FWpz8=
install: true
